project:
  type: website
  output-dir: docs
  resources:
    - assets/**
    - data/**

website:
  title: "ClimeApp"
  favicon: "images/Logo_Favicon.ico"
  page-footer:
    left: "© 2025 ClimeApp Team – Universität Bern"
    right: "This page is built with [Quarto](https://quarto.org/)"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: github
        href: https://github.com/ClimeApp/ClimeApp_development

format:
  html:
    css: styles.css
    toc: true
    toc-location: right
    include-after-body:
      - assets/script.html
