project:
  type: website
  output-dir: docs
  resources:
    - assets/**
    - data/**

website:
  favicon: "images/Logo_Favicon.ico"
  page-footer:
    left: "© 2025 ClimeApp Team – Universität Bern"
    right: |
      This page is built with [Quarto](https://quarto.org/)
      <a href="https://github.com/ClimeApp/ClimeApp_development" target="_blank">
      <br>
        <i class="fa-brands fa-github"></i> GitHub
      </a>

  
  navbar:
    logo: images/Logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Über uns
      - href: quellen.qmd
        text: Quellen
    

format:
  html:
    css: styles.css
    toc: true
    toc-location: right
    include-after-body:
      - assets/script.html
