project:
  type: website
  output-dir: docs

website:
  title: "ClimeApp"
  favicon: "images/Logo_Favicon.ico"
  page-footer:
    left: "© 2025 ClimeApp Team – Universität Bern"
    right: 
      - icon: github
        href: https://github.com/ClimeApp/ClimeApp_development
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: github
        href: https://github.com/ClimeApp/ClimeApp_development

format:
  html:
    css: styles.css
    toc: true
    toc-location: right
